// bdc 0x08a08b80 __ieee754_sqrt
#include "bdc.h"

/* fdlibm/newlib __ieee754_sqrt: bit-by-bit square root of a double using integer arithmetic only.
   Inf/NaN return x*x + x, +-0 returns x, negative x returns NaN (0/0); subnormals are normalised
   first, then the result bits are generated by shift-and-subtract and rounded to nearest. */
double __ieee754_sqrt(double x)
{
  static const double zero = 0.0;
  union { double d; struct { u32 lo; u32 hi; } w; } bits;
  s32 ix0, s0, q, m, t, i;
  u32 r, t1, s1, ix1, q1;

  bits.d = x;
  ix0 = (s32)bits.w.hi;
  ix1 = bits.w.lo;

  /* inf and NaN */
  if ((ix0 & 0x7ff00000) == 0x7ff00000) {
    return x * x + x;
  }
  /* zero and negative */
  if (ix0 <= 0) {
    if (((ix0 & 0x7fffffff) | ix1) == 0) {
      return x;
    }
    if (ix0 < 0) {
      return zero / zero;
    }
  }
  /* normalise */
  m = ix0 >> 20;
  if (m == 0) {
    while (ix0 == 0) {
      m -= 21;
      ix0 |= (s32)(ix1 >> 11);
      ix1 <<= 21;
    }
    for (i = 0; (ix0 & 0x00100000) == 0; i++) {
      ix0 <<= 1;
    }
    m -= i - 1;
    /* MIPS shifts by (32 - i) & 31, so i == 0 ors in the whole low word */
    ix0 |= (s32)(ix1 >> ((32 - i) & 31));
    ix1 <<= i;
  }
  m -= 1023;
  ix0 = (ix0 & 0x000fffff) | 0x00100000;
  if (m & 1) { /* odd m: double x to make it even */
    ix0 += ix0 + (s32)((ix1 & 0x80000000U) >> 31);
    ix1 += ix1;
  }
  m >>= 1;

  /* generate sqrt(x) bit by bit */
  ix0 += ix0 + (s32)((ix1 & 0x80000000U) >> 31);
  ix1 += ix1;
  q = q1 = s0 = s1 = 0;
  r = 0x00200000;
  while (r != 0) {
    t = s0 + (s32)r;
    if (t <= ix0) {
      s0 = t + (s32)r;
      ix0 -= t;
      q += (s32)r;
    }
    ix0 += ix0 + (s32)((ix1 & 0x80000000U) >> 31);
    ix1 += ix1;
    r >>= 1;
  }
  r = 0x80000000U;
  while (r != 0) {
    t1 = s1 + r;
    t = s0;
    if (t < ix0 || (t == ix0 && t1 <= ix1)) {
      s1 = t1 + r;
      if ((t1 & 0x80000000U) == 0x80000000U && (s1 & 0x80000000U) == 0) {
        s0 += 1;
      }
      ix0 -= t;
      if (ix1 < t1) {
        ix0 -= 1;
      }
      ix1 -= t1;
      q1 += r;
    }
    ix0 += ix0 + (s32)((ix1 & 0x80000000U) >> 31);
    ix1 += ix1;
    r >>= 1;
  }

  /* round to nearest */
  if ((ix0 | ix1) != 0) {
    if (q1 == 0xffffffffU) {
      q1 = 0;
      q += 1;
    } else {
      q1 += q1 & 1;
    }
  }
  ix0 = (q >> 1) + 0x3fe00000;
  ix1 = q1 >> 1;
  if (q & 1) {
    ix1 |= 0x80000000U;
  }
  ix0 += m << 20;
  bits.w.hi = (u32)ix0;
  bits.w.lo = ix1;
  return bits.d;
}
